[fivepaisa]
APP_NAME = "5P56139858"
APP_SOURCE = "25268"
USER_ID = "kpiO3Nfckot"
PASSWORD = "cvLDUzSKka0"
USER_KEY = "qdgWkql4y2RIPzNvVkuAU8GXDr4K0poo"
ENCRYPTION_KEY = "qc3dezuXampaQncAjs0w0C0HAKS5hMjv"
CLIENT_CODE = "56139858"
PIN = "634566"
