[5paisa]
app_name = "5P56139858"
app_source = "25268"
user_id = "kpiO3Nfckot"
password = "cvLDUzSKka0"
user_key = "qdgWkql4y2RIPzNvVkuAU8GXDr4K0poo"
encryption_key = "qc3dezuXampaQncAjs0w0C0HAKS5hMjv"
client_code = "56139858"
pin = "634566"
